apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ytt
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: default
        image: hashicorp/http-echo
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ytt
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ytt
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: default
        image: hashicorp/http-echo
        env:
        - name: BACKEND_URL
          value: backend.ytt.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ytt
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: frontend
