---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
  namespace: app-namespace-1
spec:
  selector:
    matchLabels:
      app: app-2
  replicas: 1
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: default
          image: hashicorp/http-echo
