---
apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: app-namespace-1
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: default
          image: hashicorp/http-echo
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  namespace: app-namespace-1
spec:
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678