#@ load("@ytt:data", "data")

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    releaseName: aws-load-balancer-controller
    namespace: aws-load-balancer-controller
    version: 1.8.1
    includeCRDs: true
    valuesInline:
      clusterName: application-cluster
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
      vpcId: #@ data.values.vpcId
      region: #@ data.values.region
